export enum StatusPedido {
  CRIADO = "CRIADO",
  RECEBIDO = "RECEBIDO",
  EM_PREPARACAO = "EM_PREPARACAO",
  PRONTO = "PRONTO",
  FINALIZADO = "FINALIZADO",
  ENTREGUE = "ENTREGUE",
  CANCELADO = "CANCELADO",
}
